### ISSUE TITLE
Feature: toggle using keyboard shortcut

### ISSUE THREAD

**Issue by floriensk** [garywill/toggleWebCustomFont#2]
Dear @garywill,

I believe this extension would really profit from being able to assign a keyboard shortcut to it. Since only a few websites break when custom font is disabled, I keep the extension icon in the overflow menu. This makes it a bit slow to be used, especially when repeatedly leaving the page and returning to it. A quick shortcut would resolve the issue.

A more advanced feature would be to be able to specify for the page of the currently open tab, whether custom font should be enabled. The extension could then toggle the config whenever it sees that the current tab or page has changed. But the simple shortcut would already be of great help.

**Comment by garywill** [comment]
Sorry for being delayed for so many months. 
It's done now. 
Can install the latest version from AMO.

**Comment by floriensk** [comment]
Hey, no problem, thanks a lot for the update! Great extension, don't give up the support!
